[package]
name = "libafl_fandango"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "forkserver_fuzzer"
path = "src/bin/forkserver_fuzzer.rs"
required-features = ["std"]

[features]
default = ["std"]
std = [
    "libafl/fork",
    "libafl/std",
    "libafl_bolts/std",
    "libafl_bolts/serdeany_autoreg",
]

[dependencies]
fandango = { path = ".." }

libafl = { workspace = true, features = ["rand_trait"] }
libafl_bolts = { workspace = true, features = ["rand_trait"] }
mappable-rc.workspace = true
serde = { workspace = true, features = ["alloc", "derive"] }

[dev-dependencies]
rand = { workspace = true, features = ["std_rng"] }

[lints]
workspace = true
