//! Generate EVM bytecode from `grammars/evm.fan` and report grammar k-path coverage.
//!
//! k-path coverage measures how many distinct length-`k` paths through the grammar's
//! node graph have been exercised by the generated inputs. It is a structural coverage
//! metric for grammar-based generators: the *universe* of paths is derived from the
//! grammar itself (via [`KPaths::new`]), and each generated tree marks the paths it
//! walks as covered.
//!
//! Usage:
//! ```text
//! cargo run --release --example evm_kpath --features "evm static_defs" -- [K] [SAMPLES] [SEED]
//! ```
//! Defaults: `K = 2`, `SAMPLES = 2000`, `SEED` = OS entropy.

use anyhow::{Context, Error};
use fandango::generation::Generated;
use fandango::tuple_list::tuple_list;
use fandango::typing::Structured;
use fandango::visitor::Visitor;
use fandango::visitor::write::WriteVisitor;
use fandango_core::visitor::kpath::{KPathUpdate, KPaths};
use fandango_runtime::operators::DepthLimiter;
use fandango_targets::evm::{self, TypeMut, nonterminal_start};
use rand::SeedableRng;
use rand::rngs::StdRng;
use std::num::NonZeroUsize;

/// Render a generated bytecode tree to its raw bytes.
fn to_bytes(program: &nonterminal_start) -> Result<Vec<u8>, Error> {
    Ok(WriteVisitor::new(Vec::new())
        .visit(program, 0)?
        .continue_value()
        .expect("write visitor never breaks")
        .output())
}

fn main() -> Result<(), Error> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let k: usize = args.first().map_or(Ok(2), |a| a.parse()).context("K must be a positive integer")?;
    let samples: usize = args.get(1).map_or(Ok(2000), |a| a.parse()).context("SAMPLES must be an integer")?;
    let k = NonZeroUsize::new(k).context("K must be > 0")?;

    let mut sampler = match args.get(2) {
        Some(s) => StdRng::seed_from_u64(s.parse().context("SEED must be a u64")?),
        None => StdRng::from_os_rng(),
    };

    // The generator walks the grammar structure, bounded so right-recursive bytecode
    // sequences terminate.
    let generator = DepthLimiter::new(evm::STRUCTURE.inner(), 100);
    let mut generators = tuple_list!(generator);

    // Build the k-path universe directly from the grammar graph.
    let mut kpaths = KPaths::new::<TypeMut<'static>>(k, nonterminal_start::ROOT.inner());
    let (_, total) = kpaths.k_paths();
    println!("grammar = grammars/evm.fan   k = {k}   total {k}-paths in grammar = {total}");

    let mut updater = KPathUpdate::inserting(&mut kpaths);
    let mut total_bytes = 0usize;
    let report_every = (samples / 10).max(1);

    for i in 1..=samples {
        let program = nonterminal_start::generate(&mut sampler, &mut generators, 0);
        let bytes = to_bytes(&program)?;
        if i == 1 {
            let preview: String = bytes.iter().take(32).map(|b| format!("{b:02x}")).collect();
            let ellipsis = if bytes.len() > 32 { "..." } else { "" };
            println!("sample #1 ({} bytes): 0x{preview}{ellipsis}", bytes.len());
        }
        total_bytes += bytes.len();

        // Mark every k-path this tree walks as covered.
        updater = updater
            .visit(&program, 0)
            .expect("k-path update never errors")
            .continue_value()
            .expect("k-path update never breaks");

        if i % report_every == 0 || i == samples {
            let (uncovered, total) = updater.kpaths().k_paths();
            let covered = total - uncovered;
            println!(
                "  after {i:>6} samples: covered {covered:>7} / {total}  ({:5.2}%)",
                percent(covered, total)
            );
        }
    }

    let (uncovered, total) = updater.kpaths().k_paths();
    let covered = total - uncovered;
    println!();
    println!(
        "Covered {covered} of {total} {k}-paths ({:.2}%) from {samples} programs \
         ({total_bytes} bytes of EVM bytecode total).",
        percent(covered, total)
    );

    Ok(())
}

fn percent(covered: usize, total: usize) -> f64 {
    if total == 0 {
        0.0
    } else {
        covered as f64 / total as f64 * 100.0
    }
}
