<start> ::= <scenario> ;

<scenario> ::= '{"blocks": [' <blocks> '], "nodes": [' <nodes> '], "actions": [' <actions> ']}\n' ;

<blocks> ::= '{"slot_id": 0, "block_id": "0"}, '
    '{"slot_id": 1, "block_id": "1a", "parent_id": "0"}, {"slot_id": 1, "block_id": "1b", "parent_id": "0"}, '
    '{"slot_id": 2, "block_id": "2a", "parent_id": "1a"}, {"slot_id": 2, "block_id": "2b", "parent_id": "1b"}, '
    '{"slot_id": 3, "block_id": "3a", "parent_id": "2a"}, {"slot_id": 3, "block_id": "3b", "parent_id": "2b"}, '
    '{"slot_id": 4, "block_id": "4a", "parent_id": "3a"}, {"slot_id": 4, "block_id": "4b", "parent_id": "3b"}, '
    '{"slot_id": 5, "block_id": "5a", "parent_id": "4a"}, {"slot_id": 5, "block_id": "5b", "parent_id": "4b"}, '
    '{"slot_id": 6, "block_id": "6a", "parent_id": "5a"}, {"slot_id": 6, "block_id": "6b", "parent_id": "5b"}, '
    '{"slot_id": 7, "block_id": "7a", "parent_id": "6a"}, {"slot_id": 7, "block_id": "7b", "parent_id": "6b"}, '
    '{"slot_id": 8, "block_id": "8a", "parent_id": "7a"}, {"slot_id": 8, "block_id": "8b", "parent_id": "7b"}, '
    '{"slot_id": 9, "block_id": "9a", "parent_id": "8a"}, {"slot_id": 9, "block_id": "9b", "parent_id": "8b"}, '
    '{"slot_id": 10, "block_id": "10a", "parent_id": "9a"}, {"slot_id": 10, "block_id": "10b", "parent_id": "9b"}, '
    '{"slot_id": 11, "block_id": "11a", "parent_id": "10a"}, {"slot_id": 11, "block_id": "11b", "parent_id": "10b"}, '
    '{"slot_id": 12, "block_id": "12a", "parent_id": "11a"}, {"slot_id": 12, "block_id": "12b", "parent_id": "11b"}, '
    '{"slot_id": 13, "block_id": "13a", "parent_id": "12a"}, {"slot_id": 13, "block_id": "13b", "parent_id": "12b"}, '
    '{"slot_id": 14, "block_id": "14a", "parent_id": "13a"}, {"slot_id": 14, "block_id": "14b", "parent_id": "13b"}, '
    '{"slot_id": 15, "block_id": "15a", "parent_id": "14a"}, {"slot_id": 15, "block_id": "15b", "parent_id": "14b"}' ;

<nodes> ::= <honest_nodes> ', ' <maybe_absent_nodes> ', ' <maybe_byzantine_nodes> ;
<honest_nodes> ::= '{"node_id": 0, "stake": 620000}, '
    '{"node_id": 1, "stake": 620000}, '
    '{"node_id": 2, "stake": 620000}, '
    '{"node_id": 3, "stake": 620000}, '
    '{"node_id": 4, "stake": 620000}, '
    '{"node_id": 5, "stake": 620000}, '
    '{"node_id": 6, "stake": 620000}, '
    '{"node_id": 7, "stake": 620000}, '
    '{"node_id": 8, "stake": 620000}, '
    '{"node_id": 9, "stake": 620000}' ;
<maybe_absent_nodes> ::= '{"node_id": 10, "stake": 380000}, '
    '{"node_id": 11, "stake": 380000}, '
    '{"node_id": 12, "stake": 380000}, '
    '{"node_id": 13, "stake": 380000}, '
    '{"node_id": 14, "stake": 380000}' ;
<maybe_byzantine_nodes> ::= '{"node_id": 15, "stake": 380000}, '
    '{"node_id": 16, "stake": 380000}, '
    '{"node_id": 17, "stake": 380000}, '
    '{"node_id": 18, "stake": 380000}, '
    '{"node_id": 19, "stake": 380000}' ;

<actions> ::= <slot_1_votes> ', ' <slot_2_votes> ', ' <slot_3_votes> ', ' <slot_4_votes> ', ' <slot_5_votes> ', '
    <slot_6_votes> ', ' <slot_7_votes> ', ' <slot_8_votes> ', ' <slot_9_votes> ', ' <slot_10_votes> ', '
    <slot_11_votes> ', ' <slot_12_votes> ', ' <slot_13_votes> ', ' <slot_14_votes> ', ' <slot_15_votes> ;

<slot_1_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "1' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "1' <fork> '", "action": ' <vote_kind> '}' ;

<slot_2_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "2' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "2' <fork> '", "action": ' <vote_kind> '}' ;

<slot_3_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "3' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "3' <fork> '", "action": ' <vote_kind> '}' ;

<slot_4_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "4' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "4' <fork> '", "action": ' <vote_kind> '}' ;

<slot_5_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "5' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "5' <fork> '", "action": ' <vote_kind> '}' ;

<slot_6_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "6' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "6' <fork> '", "action": ' <vote_kind> '}' ;

<slot_7_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "7' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "7' <fork> '", "action": ' <vote_kind> '}' ;

<slot_8_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "8' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "8' <fork> '", "action": ' <vote_kind> '}' ;

<slot_9_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "9' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "9' <fork> '", "action": ' <vote_kind> '}' ;

<slot_10_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "10' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "10' <fork> '", "action": ' <vote_kind> '}' ;

<slot_11_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "11' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "11' <fork> '", "action": ' <vote_kind> '}' ;

<slot_12_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "12' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "12' <fork> '", "action": ' <vote_kind> '}' ;

<slot_13_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "13' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "13' <fork> '", "action": ' <vote_kind> '}' ;

<slot_14_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "14' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "14' <fork> '", "action": ' <vote_kind> '}' ;

<slot_15_votes> ::= <maybe_action> '{"node_id": 0, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 1, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 2, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 3, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 4, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 5, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 6, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 7, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 8, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 9, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 10, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 11, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 12, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 13, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 14, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 15, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 16, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 17, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 18, "block_id": "15' <fork> '", "action": ' <vote_kind> '}, '
    <maybe_action> '{"node_id": 19, "block_id": "15' <fork> '", "action": ' <vote_kind> '}' ;

<maybe_action> ::= "" | <action> ', ' ;
<vote_kind> ::= '"VOTE_NOTAR"' | '"VOTE_NOTAR_FALLBACK"' | '"VOTE_SKIP"' | '"VOTE_SKIP_FALLBACK"' | '"VOTE_FINALIZE"' | '"VOTE_ABSENT"' ;

<action> ::= <vote_notar>
    | <vote_notar_fallback>
    | <vote_skip>
    | <vote_skip_fallback>
    | <vote_finalize>
    | <vote_absent>
    | <first_shred>
    | <replay_block_complete>
    | <sig_slot_dead>
    | <timeout> ;

<vote_notar> ::= '{"node_id": ' <node_id> ', "block_id": ' <block_id> ', "action": "VOTE_NOTAR"}' ;
<vote_notar_fallback> ::= '{"node_id": ' <node_id> ', "block_id": ' <block_id> ', "action": "VOTE_NOTAR_FALLBACK"}' ;
<vote_skip> ::= '{"node_id": ' <node_id> ', "block_id": ' <block_id> ', "action": "VOTE_SKIP"}' ;
<vote_skip_fallback> ::= '{"node_id": ' <node_id> ', "block_id": ' <block_id> ', "action": "VOTE_SKIP_FALLBACK"}' ;
<vote_finalize> ::= '{"node_id": ' <node_id> ', "block_id": ' <block_id> ', "action": "VOTE_FINALIZE"}' ;
<vote_absent> ::= '{"node_id": ' <node_id> ', "block_id": ' <block_id> ', "action": "VOTE_ABSENT"}' ;
<first_shred> ::= '{"block_id": ' <block_id> ', "action": "FIRST_SHRED"}' ;
<replay_block_complete> ::= '{"block_id": ' <block_id> ', "action": "REPLAY_BLOCK_COMPLETE"}' ;
<sig_slot_dead> ::= '{"block_id": ' <block_id> ', "action": "SIG_SLOT_DEAD"}' ;
<timeout> ::= '{"action": "TIMEOUT"}' ;

<block_id> ::= '"' <block_slot> <fork> '"' ;
<block_slot> ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "11" | "12" | "13" | "14" | "15" ;
<fork> ::= "a" | "b" ;

<node_id> ::= <honest_node_id> | <maybe_absent_node_id> | <maybe_byzantine_node_id> ;
<honest_node_id> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
<maybe_absent_node_id> ::= "10" | "11" | "12" | "13" | "14" ;
<maybe_byzantine_node_id> ::= "15" | "16" | "17" | "18" | "19" ;
